routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//admin routes
Route::get('/', function () {
    return view('pages.index');
});
Route::resource('Category','CategoryController');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $guarded=[];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use Session;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::latest()->get();
      
        return view('pages.medicine_category.index',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.medicine_category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         $category=new Category();
        $request->validate([
            'category_name' => 'required|max:255|unique:categories',
            'category_description' =>'required|max:1000',
            'status' => 'required|integer',
        
            ]);
      $category->category_name=strtoupper($request->category_name);
      $category->category_description=$request->category_description;
      $category->status=$request->status;
      $category->save();
      Session::flash('message','Category inserted successfully!!!!');
      return redirect(route('Category.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);

        return view('pages.medicine_category.edit',compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category=Category::find($id);
        $request->validate([
            'category_name' => 'required|max:255',
            'category_description' =>'required|max:1000',
            'status' => 'required|integer',
        
            ]);

      $category->category_name=$request->category_name;
      $category->category_description=$request->category_description;
      $category->status=$request->status;
      $category->save();
      Session::flash('message','Category updated successfully!!!!');
      return redirect(route('Category.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         $category=Category::find($id);
         $category->delete();
         Session::flash('message','Category deleted successfully!!!!');
         return redirect(route('Category.index'));
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/include/_footer.blade.php
 <div class="footer-left">
          <div class="mg-b-2">Copyright &copy; 2017. Bracket Plus. All Rights Reserved.</div>
          <div>Attentively and carefully made by ThemePixels.</div>
        </div>
        <div class="footer-right d-flex align-items-center">
          <span class="tx-uppercase mg-r-10">Share:</span>
          <a target="_blank" class="pd-x-5" href="https://www.facebook.com/sharer/sharer.php?u=http%3A//themepixels.me/bracketplus/intro"><i class="fab fa-facebook tx-20"></i></a>
          <a target="_blank" class="pd-x-5" href="https://twitter.com/home?status=Bracket%20Plus,%20your%20best%20choice%20for%20premium%20quality%20admin%20template%20from%20Bootstrap.%20Get%20it%20now%20at%20http%3A//themepixels.me/bracketplus/intro"><i class="fab fa-twitter tx-20"></i></a>
  </div>

resources/views/include/_head.blade.php
   <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <!-- Twitter -->
    <meta name="twitter:site" content="@themepixels">
    <meta name="twitter:creator" content="@themepixels">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="Bracket Plus">
    <meta name="twitter:description" content="Premium Quality and Responsive UI for Dashboard.">
    <meta name="twitter:image" content="http://themepixels.me/bracketplus/img/bracketplus-social.png">

    <!-- Facebook -->
    <meta property="og:url" content="http://themepixels.me/bracketplus">
    <meta property="og:title" content="Bracket Plus">
    <meta property="og:description" content="Premium Quality and Responsive UI for Dashboard.">

    <meta property="og:image" content="http://themepixels.me/bracketplus/img/bracketplus-social.png">
    <meta property="og:image:secure_url" content="http://themepixels.me/bracketplus/img/bracketplus-social.png">
    <meta property="og:image:type" content="image/png">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="600">

    <!-- Meta -->
    <meta name="description" content="Premium Quality and Responsive UI for Dashboard.">
    <meta name="author" content="ThemePixels">

    <title>Bracket Plus Responsive Bootstrap 4 Admin Template</title>

    <!-- vendor css -->
    <link href="{{asset('public/user/lib/@fortawesome/fontawesome-free/css/all.min.css')}}" rel="stylesheet">
    <link href="{{asset('public/user/lib/ionicons/css/ionicons.min.css')}}" rel="stylesheet">
    <link href="{{asset('public/user/lib/rickshaw/rickshaw.min.css')}}" rel="stylesheet">
    <link href="{{asset('public/user/lib/select2/css/select2.min.css')}}" rel="stylesheet">
    

    <!-- Bracket CSS -->
    <link rel="stylesheet" href="{{asset('public/user/css/bracket.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    @yield('css')

resources/views/include/_headpannel.blade.php
 <div class="br-header">
      <div class="br-header-left">
        <div class="navicon-left hidden-md-down"><a id="btnLeftMenu" href=""><i class="icon ion-navicon-round"></i></a></div>
        <div class="navicon-left hidden-lg-up"><a id="btnLeftMenuMobile" href=""><i class="icon ion-navicon-round"></i></a></div>
        
      </div><!-- br-header-left -->
      <div class="br-header-right">
        <nav class="nav">
          <div class="dropdown">
            <a href="" class="nav-link pd-x-7 pos-relative" data-toggle="dropdown">
              <i class="icon ion-ios-email-outline tx-24"></i>
              <!-- start: if statement -->
              <span class="square-8 bg-danger pos-absolute t-15 r-0 rounded-circle"></span>
              <!-- end: if statement -->
            </a>
            <div class="dropdown-menu dropdown-menu-header">
              <div class="dropdown-menu-label">
                <label>Messages</label>
                <a href="">+ Add New Message</a>
              </div><!-- d-flex -->

              <div class="media-list">
                <!-- loop starts here -->
                <a href="" class="media-list-link">
                  <div class="media">
                    <img src="https://via.placeholder.com/500" alt="">
                    <div class="media-body">
                      <div>
                        <p>Donna Seay</p>
                        <span>2 minutes ago</span>
                      </div><!-- d-flex -->
                      <p>A wonderful serenity has taken possession of my entire soul, like these sweet mornings of spring.</p>
                    </div>
                  </div><!-- media -->
                </a>
                <!-- loop ends here -->
                <a href="" class="media-list-link read">
                  <div class="media">
                    <img src="https://via.placeholder.com/500" alt="">
                    <div class="media-body">
                      <div>
                        <p>Samantha Francis</p>
                        <span>3 hours ago</span>
                      </div><!-- d-flex -->
                      <p>My entire soul, like these sweet mornings of spring.</p>
                    </div>
                  </div><!-- media -->
                </a>
                <a href="" class="media-list-link read">
                  <div class="media">
                    <img src="https://via.placeholder.com/500" alt="">
                    <div class="media-body">
                      <div>
                        <p>Robert Walker</p>
                        <span>5 hours ago</span>
                      </div><!-- d-flex -->
                      <p>I should be incapable of drawing a single stroke at the present moment...</p>
                    </div>
                  </div><!-- media -->
                </a>
                <a href="" class="media-list-link read">
                  <div class="media">
                    <img src="https://via.placeholder.com/500" alt="">
                    <div class="media-body">
                      <div>
                        <p>Larry Smith</p>
                        <span>Yesterday</span>
                      </div><!-- d-flex -->
                      <p>When, while the lovely valley teems with vapour around me, and the meridian sun strikes...</p>
                    </div>
                  </div><!-- media -->
                </a>
                <div class="dropdown-footer">
                  <a href=""><i class="fas fa-angle-down"></i> Show All Messages</a>
                </div>
              </div><!-- media-list -->
            </div><!-- dropdown-menu -->
          </div><!-- dropdown -->
          <div class="dropdown">
            <a href="" class="nav-link pd-x-7 pos-relative" data-toggle="dropdown">
              <i class="icon ion-ios-bell-outline tx-24"></i>
              <!-- start: if statement -->
              <span class="square-8 bg-danger pos-absolute t-15 r-5 rounded-circle"></span>
              <!-- end: if statement -->
            </a>
            <div class="dropdown-menu dropdown-menu-header">
              <div class="dropdown-menu-label">
                <label>Notifications</label>
                <a href="">Mark All as Read</a>
              </div><!-- d-flex -->

              <div class="media-list">
                <!-- loop starts here -->
                <a href="" class="media-list-link read">
                  <div class="media">
                    <img src="https://via.placeholder.com/500" alt="">
                    <div class="media-body">
                      <p class="noti-text"><strong>Suzzeth Bungaos</strong> tagged you and 18 others in a post.</p>
                      <span>October 03, 2017 8:45am</span>
                    </div>
                  </div><!-- media -->
                </a>
                <!-- loop ends here -->
                <a href="" class="media-list-link read">
                  <div class="media">
                    <img src="https://via.placeholder.com/500" alt="">
                    <div class="media-body">
                      <p class="noti-text"><strong>Mellisa Brown</strong> appreciated your work <strong>The Social Network</strong></p>
                      <span>October 02, 2017 12:44am</span>
                    </div>
                  </div><!-- media -->
                </a>
                <a href="" class="media-list-link read">
                  <div class="media">
                    <img src="https://via.placeholder.com/500" alt="">
                    <div class="media-body">
                      <p class="noti-text">20+ new items added are for sale in your <strong>Sale Group</strong></p>
                      <span>October 01, 2017 10:20pm</span>
                    </div>
                  </div><!-- media -->
                </a>
                <a href="" class="media-list-link read">
                  <div class="media">
                    <img src="https://via.placeholder.com/500" alt="">
                    <div class="media-body">
                      <p class="noti-text"><strong>Julius Erving</strong> wants to connect with you on your conversation with <strong>Ronnie Mara</strong></p>
                      <span>October 01, 2017 6:08pm</span>
                    </div>
                  </div><!-- media -->
                </a>
                <div class="dropdown-footer">
                  <a href=""><i class="fas fa-angle-down"></i> Show All Notifications</a>
                </div>
              </div><!-- media-list -->
            </div><!-- dropdown-menu -->
          </div><!-- dropdown -->
          <div class="dropdown">
            <a href="" class="nav-link nav-link-profile" data-toggle="dropdown">
              <span class="logged-name hidden-md-down">Katherine</span>
              <img src="https://via.placeholder.com/500" class="wd-32 rounded-circle" alt="">
              <span class="square-10 bg-success"></span>
            </a>
            <div class="dropdown-menu dropdown-menu-header wd-250">
              <div class="tx-center">
                <a href=""><img src="https://via.placeholder.com/500" class="wd-80 rounded-circle" alt=""></a>
                <h6 class="logged-fullname">Katherine P. Lumaad</h6>
                <p>youremail@domain.com</p>
              </div>
              <hr>
              <div class="tx-center">
                <span class="profile-earning-label">Earnings After Taxes</span>
                <h3 class="profile-earning-amount">$13,230 <i class="icon ion-ios-arrow-thin-up tx-success"></i></h3>
                <span class="profile-earning-text">Based on list price.</span>
              </div>
              <hr>
              <ul class="list-unstyled user-profile-nav">
                <li><a href=""><i class="icon ion-ios-person"></i> Edit Profile</a></li>
                <li><a href=""><i class="icon ion-ios-gear"></i> Settings</a></li>
                <li><a href=""><i class="icon ion-ios-download"></i> Downloads</a></li>
                <li><a href=""><i class="icon ion-ios-star"></i> Favorites</a></li>
                <li><a href=""><i class="icon ion-ios-folder"></i> Collections</a></li>
                <li><a href=""><i class="icon ion-power"></i> Sign Out</a></li>
              </ul>
            </div><!-- dropdown-menu -->
          </div><!-- dropdown -->
        </nav>
       
      </div><!-- br-header-right -->
    </div><!-- br-header -->

resources/views/include/_javascript.blade.php
    <script src="{{asset('/public/user/lib/jquery/jquery.min.js')}}"></script>
    <script src="{{asset('/public/user/lib/jquery-ui/ui/widgets/datepicker.js')}}"></script>
    <script src="{{asset('/public/user/lib/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
    <script src="{{asset('/public/user/lib/perfect-scrollbar/perfect-scrollbar.min.js')}}"></script>
    <script src="{{asset('/public/user/lib/moment/min/moment.min.js')}}"></script>
    <script src="{{asset('/public/user/lib/peity/jquery.peity.min.js')}}"></script>
    <script src="{{asset('/public/user/lib/rickshaw/vendor/d3.min.js')}}"></script>
    <script src="{{asset('/public/user/lib/rickshaw/vendor/d3.layout.min.js')}}"></script>
    <script src="{{asset('/public/user/lib/rickshaw/rickshaw.min.js')}}"></script>
    <script src="{{asset('/public/user/lib/jquery.flot/jquery.flot.js')}}"></script>
    <script src="{{asset('/public/user/lib/jquery.flot/jquery.flot.resize.js')}}"></script>
    <script src="{{asset('/public/user/lib/flot-spline/js/jquery.flot.spline.min.js')}}"></script>
    <script src="{{asset('/public/user/lib/jquery-sparkline/jquery.sparkline.min.js')}}"></script>
    <script src="{{asset('/public/user/lib/echarts/echarts.min.js')}}"></script>
    <script src="{{asset('/public/user/lib/select2/js/select2.full.min.js')}}"></script>
    <script src="http://maps.google.com/maps/api/js?key=AIzaSyAq8o5-8Y5pudbJMJtDFzb8aHiWJufa5fg"></script>
    <script src="{{asset('/public/user/lib/gmaps/gmaps.min.js')}}"></script>
    <script src="{{asset('/public/user/js/bracket.js')}}"></script>
    <script src="{{asset('/public/user/js/map.shiftworker.js')}}"></script>
    <script src="{{asset('/public/user/js/ResizeSensor.js')}}"></script>
    <script src="{{asset('/public/user/js/dashboard.js')}}"></script>
    <script>
      $(function(){
        'use strict'

        // FOR DEMO ONLY
        // menu collapsed by default during first page load or refresh with screen
        // having a size between 992px and 1299px. This is intended on this page only
        // for better viewing of widgets demo.
        $(window).resize(function(){
          minimizeMenu();
        });

        minimizeMenu();

        function minimizeMenu() {
          if(window.matchMedia('(min-width: 992px)').matches && window.matchMedia('(max-width: 1299px)').matches) {
            // show only the icons and hide left menu label by default
            $('.menu-item-label,.menu-item-arrow').addClass('op-lg-0-force d-lg-none');
            $('body').addClass('collapsed-menu');
            $('.show-sub + .br-menu-sub').slideUp();
          } else if(window.matchMedia('(min-width: 1300px)').matches && !$('body').hasClass('collapsed-menu')) {
            $('.menu-item-label,.menu-item-arrow').removeClass('op-lg-0-force d-lg-none');
            $('body').removeClass('collapsed-menu');
            $('.show-sub + .br-menu-sub').slideDown();
          }
        }
      });
    </script>

    @yield('js')

resources/views/include/_leftsidebar.blade.php
 <label class="sidebar-label pd-x-10 mg-t-20 op-3">Navigation</label>
      <ul class="br-sideleft-menu">
        <li class="br-menu-item">
          <a href="index.html" class="br-menu-link active">
            <i class="menu-item-icon icon ion-ios-home-outline tx-24"></i>
            <span class="menu-item-label">Dashboard</span>
          </a><!-- br-menu-link -->
        </li><!-- br-menu-item -->
      
      
        <li class="br-menu-item">
          <a href="#" class="br-menu-link with-sub">
            <i class="menu-item-icon fa fa-medkit tx-24"></i>
            <span class="menu-item-label">Manage Medicine</span>
          </a><!-- br-menu-link -->
          <ul class="br-menu-sub">
            <li class="sub-item"><a href="navigation.html" class="sub-link">Basic Nav</a></li>
            <li class="sub-item"><a href="navigation-layouts.html" class="sub-link">Nav Layouts</a></li>
            <li class="sub-item"><a href="navigation-effects.html" class="sub-link">Nav Effects</a></li>
          </ul>
        </li><!-- br-menu-item -->
        <li class="br-menu-item">
          <a href="#" class="br-menu-link with-sub">
            <i class="menu-item-icon fa fa-search tx-20"></i>
            <span class="menu-item-label">Seacrh Medicine</span>
          </a><!-- br-menu-link -->
          <ul class="br-menu-sub">
            <li class="sub-item"><a href="chart-morris.html" class="sub-link">Morris Charts</a></li>
            <li class="sub-item"><a href="chart-flot.html" class="sub-link">Flot Charts</a></li>
            <li class="sub-item"><a href="chart-chartjs.html" class="sub-link">Chart JS</a></li>
            <li class="sub-item"><a href="chart-echarts.html" class="sub-link">ECharts</a></li>
            <li class="sub-item"><a href="chart-rickshaw.html" class="sub-link">Rickshaw</a></li>
            <li class="sub-item"><a href="chart-chartist.html" class="sub-link">Chartist</a></li>
            <li class="sub-item"><a href="chart-sparkline.html" class="sub-link">Sparkline</a></li>
            <li class="sub-item"><a href="chart-peity.html" class="sub-link">Peity</a></li>
          </ul>
        </li>
         <li class="br-menu-item">
          <a href="#" class="br-menu-link with-sub">
            <i class="menu-item-icon fa fa-medkit tx-24"></i>
            <span class="menu-item-label">Medicine Categories</span>
          </a><!-- br-menu-link -->
          <ul class="br-menu-sub">
            <li class="sub-item"><a href="{{route('Category.index')}}" class="sub-link">Category List</a></li>
            <li class="sub-item"><a href="{{route('Category.create')}}" class="sub-link">Add New Category</a></li>
            
          </ul>
        </li><!-- br-menu-item -->

       

      <br>

resources/views/include/_message.blade.php
@if(Session::has('message'))
   <div class="alert alert-success" role="alert">
   <strong>Success:</strong>{{Session::get('message')}}
   </div>
@endif

@if(count($errors)>0)
   <div class="alert alert-success" role="alert">
   <strong>Errors:</strong>
   <ul>
   	  @foreach($errors->all() as $error)
   	  <li>{{$error}}</li>
   	  @endforeach
   </ul>
   </div>
@endif

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>

    @include('include._head')

  </head>

  <body>

    <!-- ########## START: LEFT PANEL ########## -->
    <div class="br-logo"><a href=""><span>[</span>Feits <i>PMS</i><span>]</span></a></div>
    <div class="br-sideleft sideleft-scrollbar">
      @include('include._leftsidebar')
    </div><!-- br-sideleft -->
    <!-- ########## END: LEFT PANEL ########## -->



    <!-- ########## START: HEAD PANEL ########## -->
    @include('include._headpannel')
   
    <!-- ########## END: HEAD PANEL ########## -->


   


    <!-- ########## START: MAIN PANEL ########## -->
    <div class="br-mainpanel">
      @yield('content')

      <footer class="br-footer">

         @include('include._footer')
       
      </footer>
    </div><!-- br-mainpanel -->
    <!-- ########## END: MAIN PANEL ########## -->


<!-- ########## javascript ########## -->
     @include('include._javascript')

    
  </body>
</html>

resources/views/pages/medicine_category/create.blade.php
@extends('layouts.master')
@section('css')


<script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
<script type="text/javascript">
  tinymce.init({
    selector: '#mytextarea'
  });
  
  </script>
@endsection

@section('content')
<br>
   
      
      <div class="br-pagebody">
        <div class="br-section-wrapper">
           @include('include._message')
          <div class="row">

            <div class="col-lg-3">
                <h5>New Medicine Category</h5>
            </div> 
            <div class="col-lg-3 offset-lg-6">        
                <a href="{{route('Category.index')}}" class="btn btn-primary">All Medicine Category List</a>
            </div>
        </div>
          <hr>
          <div class="row">
            <div cla></div>
          </div>

          <div class="form-layout form-layout-1">
            <form action="{{route('Category.store')}}" method="post">
              @csrf
              <div class="row">
                <div class="col-lg-6">
                  <div class="form-group">
                  <label class="form-control-label">Category Name <span class="tx-danger">*</span></label>
                  <input class="form-control" type="text" name="category_name" value="" placeholder="Enter Medicine Category">
                </div>
                
              </div>

              <div class="col-lg-6">
                 <div class="form-group">
                         <label  class="form-control-label">Choose Status</label>

                         <select class="chosen-select form-control" name="status" id="form-field-select-3" data-placeholder="Choose a status">
                                  
                                        <option value="1">Active</option>
                                        <option value="0">Inactive</option>
                          </select>
                                      
                                
                   </div>
                
              </div>
             </div> 
           
         
                  

                <div class="form-group">
                      <label class="control-label">Category description <span class="tx-danger">*</span></label>
                      <div>
                          <textarea id="mytextarea" name="category_description" >
                              {{old('category_description')}}
                          </textarea>
                                
                      </div>
                </div>


                

              <div class="form-layout-footer">
                <input type="submit" value="Save" class="btn btn-primary">
             
              </div><!-- form-layout-footer -->

             </form> 
            
                
           
           
            </div><!-- row -->

           
          </div><!-- form-layout -->
        </div>

@endsection

@section('js')

@endsection

resources/views/pages/medicine_category/index.blade.php
 @extends('layouts.master')
 @section('css')


   
 @endsection
 @section('content')
 
     <br>
      

      <div class="br-pagebody">
        <div class="br-section-wrapper">

           <div class="row">

            <div class="col-lg-3">
                <h5>All Medicine Category List</h5>
            </div> 
            <div class="col-lg-3 offset-lg-6">        
                <a href="{{route('Category.create')}}" class="btn btn-primary">Add New Medicine Category</a>
            </div>
           </div>
          
         <br>

              <div class="bd bd-gray-300 rounded table-responsive">
            <table class="table table-striped mg-b-0">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Category Name</th>
                  <th>Category Description</th>
                  <th>Status</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody>
                @foreach($categories as $category)
                <tr>
                  <th scope="row">{{$category->id+1}}</th>
                  <td>{{$category->category_name}}</td>
                  <td>{!!$category->category_description!!}</td>
                  <td class="left">
                         @if($category->status==1)
                          <span class="label label-success">Active</span>
                          @else
                          <span class="label label-danger">Inactive</span>
                           @endif
                                    
                </td>
                <td>
                    <div class="row">
                      <div class="col-lg-2">
                        <a href="{{ route('Category.edit',$category->id)  }}" class="btn btn-sm btn-success" title="Edit">
                          <i class="fa fa-pencil-square-o"></i>
                          </a>
                        
                      </div>
                       <div class="col-lg-2">
                         <form action="{{route('Category.destroy', $category->id)}}" method="post">
                                @csrf
                                @method("DELETE")
                                
                             <button class="btn btn-sm btn-danger" onclick="return confirm('Are you sure to delete?')"><i class="fa fa-trash"></i></button>
                             </form> 
                       </div>
                       
                       </div>
                      
                              
                          


                   </td>
                </tr>
               @endforeach
               
              </tbody>
            </table>
          </div><!-- bd -->
        </div>
      @endsection

      @section('js')
  

  
      @endsection